# Generated by Django 5.0.1 on 2025-09-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Поддерживает простые переносы строк', verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('accent_color', models.CharField(default='#111827', help_text='HEX цвет для рамки/фона блока', max_length=7, verbose_name='Цвет акцента')),
                ('priority', models.IntegerField(default=0, help_text='Влияет на размер блока (больше = больше площадь)', verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
